config/routes.rb
Rails.application.routes.draw do
  root "sessions#index"

  get "/menu", to: "menu#index"
  get "/account", to: "users#show"
  get "/", to: "sessions#index"
  get "/login", to: "sessions#new"
  post "/login", to: "sessions#create"
  delete "/logout", to: "sessions#destroy"

  scope :menu, as: "menu" do
    resources :items, param: :item_name
    resources :categories, param: :category_name
  end

  scope :admin, as: "admin" do
    get "/dashboard", to: "admin#show"
  end

  resources :cart_items, only: [:create, :update, :destroy]
  get "/cart", to: "cart_items#index"
  post "/checkout", to: "orders#create"

  resources :orders do
    member do # for an individual order
      get "cancel"
      get "paid"
      get "complete"
    end
  end

  get "errors/file_not_found"
  get "errors/unprocessable"
  get "errors/internal_server_error"

  match "/404", to: "errors#file_not_found", via: :all
  match "/422", to: "errors#unprocessable", via: :all
  match "/500", to: "errors#internal_server_error", via: :all
end

app/views/admin/show.html.erb
<h1>Admin Dashboard</h1>
<% if @orders.count == 0 %>
  <h1>Cheer up! Business will come.</h1>
<% end %>

<div class="col-sm-3" id="admin-buttons">
  <p><%= link_to "Create New Menu Item", new_menu_item_path(@item), class: "btn btn-success" %></p>
</div>
<div class="col-sm-3" id="admin-buttons">
  <p><%= link_to "Create New Category", new_menu_category_path(@item), class: "btn btn-success" %></p>
</div>
<div class="col-sm-3" id="admin-buttons">
  <p><%= link_to "See All Items", menu_path, class: "btn btn-success" %></p>
</div>
<div class="col-sm-3" id="admin-buttons">
  <p><%= link_to "See All Categories", menu_categories_path, class: "btn btn-success" %></p>
</div>
<br>
<br>
<h3> Orders by Status:</h3>

<div class="orders_color_white">
<ul class="nav nav-tabs" id="myTab">
  <li class="active"><a href="#all-orders">All Orders <span class="badge"><%= @orders.count %></span></a></li>
  <li><a href="#ordered">Ordered <span class="badge"><%= @orders.ordered.count %></span></a></li>
  <li><a href="#paid">Paid <span class="badge"><%= @orders.paid.count %></span></a></li>
  <li><a href="#cancelled">Cancelled <span class="badge"><%= @orders.cancelled.count %></span></a></li>
  <li><a href="#completed">Completed <span class="badge"><%= @orders.completed.count %></span></a></li>
</ul>

<div id='content' class="tab-content">
  <div class="tab-pane active" id="all-orders">
    <table class="table">
      <tr>
        <th>Order ID</th>
        <th>Customer</th>
        <th>Customer Email</th>
        <th>Date Ordered</th>
        <th>Status</th>
      </tr>
      <% @orders.each do |order| %>
      <tr>
        <td><%= link_to "Order #{order.id}", order %></td>
        <td><%= link_to "#{order.user.full_name}", account_path(order.user) %></td>
        <td><%= link_to "#{order.user.email}", account_path(order.user) %></td>

        <td><%= format_time(order.created_at) %></td>
        <td><%= order.status %></td>
      </tr>
      <% end %>
    </table>
  </div>

  <div class="tab-pane" id="ordered">
    <table class="table">
      <tr>
        <th>Order ID</th>
        <th>Customer</th>
        <th>Customer Email</th>
        <th>Date Ordered</th>
        <th>Status</th>
        <th>Action</th>
      </tr>
      <% @orders.ordered.each do |order| %>
      <tr>
        <td><%= link_to "Order #{order.id}", order_path(order) %></td>
        <td><%= link_to "#{order.user.full_name}", account_path(order.user) %></td>
        <td><%= link_to "#{order.user.email}", account_path(order.user) %></td>

        <td><%= format_time(order.created_at) %></td>
        <td><%= order.status %></td>
        <td><%= link_to "Cancel Order", cancel_order_path(order), class: "btn btn-xs btn-danger" %>
            <%= link_to "Mark as Paid", paid_order_path(order), class: "btn btn-xs btn-info" %></td>
      </tr>
      <% end %>
    </table>
  </div>

  <div class="tab-pane" id="paid">
    <table class="table">
      <tr>
        <th>Order ID</th>
        <th>Customer</th>
        <th>Customer Email</th>
        <th>Date Ordered</th>
        <th>Status</th>
        <th>Actions</th>
      </tr>
      <% @orders.paid.each do |order| %>
      <tr>
        <td><%= link_to "Order #{order.id}", order_path(order) %></td>
        <td><%= link_to "#{order.user.full_name}", account_path(order.user) %></td>
        <td><%= link_to "#{order.user.email}", account_path(order.user) %></td>

        <td><%= format_time(order.created_at) %></td>
        <td><%= order.status %></td>
        <td><%= link_to "Cancel Order", cancel_order_path(order), class: "btn btn-xs btn-danger" %>
            <%= link_to "Mark as Completed", complete_order_path(order), class: "btn btn-xs btn-primary" %></td>
      </tr>
      <% end %>
    </table>
  </div>

  <div class="tab-pane" id="cancelled">
    <table class="table">
      <tr>
        <th>Order ID</th>
        <th>Customer</th>
        <th>Customer Email</th>
        <th>Date Ordered</th>
        <th>Date Cancelled</th>
        <th>Status</th>
      </tr>
      <% @orders.cancelled.each do |order| %>
      <tr>
        <td><%= link_to "Order #{order.id}", order_path(order) %></td>
        <td><%= link_to "#{order.user.full_name}", account_path(order.user) %></td>
        <td><%= link_to "#{order.user.email}", account_path(order.user) %></td>

        <td><%= format_time(order.created_at) %></td>
        <td><%= format_time(order.updated_at) %></td>
        <td><%= order.status %></td>
      </tr>
      <% end %>
    </table>
  </div>

  <div class="tab-pane" id="completed">
    <table class="table">
      <tr>
        <th>Order ID</th>
        <th>Customer</th>
        <th>Customer Email</th>
        <th>Date Ordered</th>
        <th>Date Completed</th>
        <th>Status</th>
      </tr>
      <% @orders.completed.each do |order| %>
      <tr>
        <td><%= link_to "Order #{order.id}", order_path(order) %></td>
        <td><%= link_to "#{order.user.full_name}", account_path(order.user) %></td>
        <td><%= link_to "#{order.user.email}", account_path(order.user) %></td>
        <td><%= format_time(order.created_at) %></td>
        <td><%= format_time(order.updated_at) %></td>
        <td><%= order.status %></td>
      </tr>
      <% end %>
    </table>
  </div>
</div>
</div>
<script>
  $('#myTab a').click(function (e) {
    e.preventDefault()
    $(this).tab('show')
  })
</script