config/routes.rb
Rails.application.routes.draw do
  root "sessions#index"

  get "/menu", to: "menu#index"
  get "/account", to: "users#show"
  get "/", to: "sessions#index"
  get "/login", to: "sessions#new"
  post "/login", to: "sessions#create"
  delete "/logout", to: "sessions#destroy"

  scope :menu, as: "menu" do
    resources :items, param: :item_name
    resources :categories, param: :category_name
  end

  scope :admin, as: "admin" do
    get "/dashboard", to: "admin#show"
  end

  resources :cart_items, only: [:create, :update, :destroy]
  get "/cart", to: "cart_items#index"
  post "/checkout", to: "orders#create"

  resources :orders do
    member do # for an individual order
      get "cancel"
      get "paid"
      get "complete"
    end
  end

  get "errors/file_not_found"
  get "errors/unprocessable"
  get "errors/internal_server_error"

  match "/404", to: "errors#file_not_found", via: :all
  match "/422", to: "errors#unprocessable", via: :all
  match "/500", to: "errors#internal_server_error", via: :all
end

app/controllers/cart_items_controller.rb
class CartItemsController < ApplicationController
  def create
    item = Item.find_by(parameterized_name: params[:item])
    cart_data
    @cart.add_item(item)
    flash[:notice] = "You have #{pluralize(@cart.item_quantity(item), item.name)} in your cart."
    redirect_to :back
  end

  def index
    @cart
  end

  def update
    item = Item.find(params[:id])
    @cart.remove_item(item)
    cart_data
    flash[:notice] = "The item has been removed from your cart."
    redirect_to cart_path
  end

  def destroy
    item = Item.find(params[:id])
    @cart.remove_all_of_item(item)
    flash[:notice] = "The item has been entirely removed from your cart."
    redirect_to cart_path
  end
end

app/views/cart_items/index.html.erb
<h1>Your Cart</h1>

<% @cart.display_items.each do |item,quantity| %>
  <div class="col-sm-4" id="checkout-item">
    <%= image_tag item.image.url, class: "menu-image image-background"%><br/>
    <%= link_to item.display_name, menu_item_path(item) %><br>
    Quantity: <%= quantity %><br>
    Price Per Unit: <%= number_to_currency(item.price) %><br>
    Total For This Item: <%= number_to_currency(item.price * quantity) %></p>
    <div class="btn-group">
      <%= link_to cart_items_path(item: item), method: :post, class: "btn btn-default" do %>
      <span class="glyphicon glyphicon-arrow-up" aria-hidden="true"></span>
      <% end %>
      <%= link_to cart_item_path(id: item.id), method: :patch, class: "btn btn-default" do %>
      <span class="glyphicon glyphicon-arrow-down" aria-hidden="true"></span>
      <% end %>
    </div>
    <%= link_to "Remove All", cart_item_path(id: item.id), method: :delete, class: "btn btn-default" %>
  </div>
<% end %>

<div class="col-xs-12" id="checkout-total">
  <p>Total Items: <%= @cart.count_total %></p>
  <p>Total Price: <%= number_to_currency(@cart.total_price) %></p>  </p>
  <%= button_to "Checkout", checkout_path, method: :post %>
</div>