config/routes.rb
Rails.application.routes.draw do
  root "sessions#index"

  get "/menu", to: "menu#index"
  get "/account", to: "users#show"
  get "/", to: "sessions#index"
  get "/login", to: "sessions#new"
  post "/login", to: "sessions#create"
  delete "/logout", to: "sessions#destroy"

  scope :menu, as: "menu" do
    resources :items, param: :item_name
    resources :categories, param: :category_name
  end

  scope :admin, as: "admin" do
    get "/dashboard", to: "admin#show"
  end

  resources :cart_items, only: [:create, :update, :destroy]
  get "/cart", to: "cart_items#index"
  post "/checkout", to: "orders#create"

  resources :orders do
    member do # for an individual order
      get "cancel"
      get "paid"
      get "complete"
    end
  end

  get "errors/file_not_found"
  get "errors/unprocessable"
  get "errors/internal_server_error"

  match "/404", to: "errors#file_not_found", via: :all
  match "/422", to: "errors#unprocessable", via: :all
  match "/500", to: "errors#internal_server_error", via: :all
end

app/models/item.rb
class Item < ActiveRecord::Base
  has_many :item_categories
  has_many :categories, -> { uniq }, through: :item_categories
  has_many :item_orders
  has_many :orders, through: :item_orders

  scope :active_items, -> { where(status: "active").order_by_id }
  scope :retired_items, -> { where(status: "retired").order_by_id }

  validates :name, presence: true, uniqueness: true
  validates :description, :price, presence: true
  validates :price, numericality: { greater_than: 0 }

  before_validation :parameterize, :downcase_name

  has_attached_file :image, styles: { large: "500x340>", medium: "250x170>", thumb: "100x100>" }, default_url: "cookie-monster.jpg"
  validates_attachment :image, content_type: { content_type: ["image/jpg", "image/jpeg", "image/png", "image/gif"] }

  def to_param
    "#{name.parameterize}"
  end

  def parameterize
    return if name.nil?
    self.parameterized_name = name.parameterize
  end

  def display_name
    name.titleize
  end

  private

  def self.order_by_id
    order(:id).reverse
  end

  def downcase_name
    return if name.nil?
    name.downcase!
  end
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  def show
    @item = Item.find_by(parameterized_name: params[:item_name])
  end

  def new
    @item = Item.new
    authorize! :new, @item
  end

  def create
    @item = Item.new(item_params)
    if @item.save
      update_categories
      flash[:success] = "New item has been created!"
      redirect_to menu_item_path(@item)
    else
      flash[:error] = "Attributes missing"
      redirect_to new_menu_item_path
    end
  end

  def edit
    @item = Item.find_by(parameterized_name: params[:item_name])
    authorize! :edit, @item
  end

  def update
    @item = Item.find_by(parameterized_name: params[:item_name])
    if @item.update(item_params)
      update_categories
      flash[:success] = "Item has been successfully updated!"
      redirect_to menu_item_path(@item)
    else
      flash[:error] = "Attributes missing."
      redirect_to :back
    end
  end

  private

  def update_categories
    ItemCategory.destroy_all(item_id: @item.id)
    params[:category_ids].each do |category|
      category_id = category.to_i
      ItemCategory.create(item_id: @item.id, category_id: category_id)
    end
  end

  def item_params
    params.require(:item).permit(:name, :description, :price, :image, :category_ids, :status)
  end
end

app/views/items/_form.html.erb
<%= form_for [:menu, @item], :html => { :multipart => true } do |f| %>
  <p>
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </p>
  <p>
    <%= f.label :description %><br />
    <%= f.text_field :description %>
  </p>
  <p>
    <%= f.label :price %><br />
    <%= f.text_field :price %>
  </p>
  <p>
    <%= f.label "Category:" %>
    <% Category.all.each do |category| %>
      <%= check_box_tag 'category_ids[]', category.id, @item.categories.include?(category)%>
      <%= category.name %>
    <% end %>
  </p>
  <p>
  <%= f.label "Status: ", class: "status-label" %>
  <%= f.select(:status, options_for_select([["active", "active"], ["retired", "retired"]]), selected: @item.status) %>
  </p>
  <p>
  <%= f.label :select_image %><br />
  <%= f.file_field :image %>
  </p>
  <%= f.submit "Submit", class: 'btn btn-default'%>
<% end %>

app/views/items/edit.html.erb
<h1>Edit Item Page</h1>

<h2>Please edit your item:</h2>
<%= render "form" %>

app/views/items/new.html.erb
<h1>New Item Page</h1>

<h2>Please enter your new item:</h2>
<%= render "form" %>

app/views/items/show.html.erb
<h1><%= @item.display_name %></h1>
<p><%= image_tag @item.image.url(:large) %></p>
<p>Description: <%= @item.description %></p>
<p>Price: <%= number_to_currency(@item.price) %></p>
<% if @item.status == "active" %>
  <p><%= button_to "Add to Cart", cart_items_path(item: @item), class: "btn btn-default" %></p>
<% end %>

<% if current_user.try(:role) == "admin" %>
  <p><%= link_to "Edit Item", edit_menu_item_path(@item), class: "btn btn-success" %>
</p>
<% end %>