config/routes.rb
Rails.application.routes.draw do
  root "sessions#index"

  get "/menu", to: "menu#index"
  get "/account", to: "users#show"
  get "/", to: "sessions#index"
  get "/login", to: "sessions#new"
  post "/login", to: "sessions#create"
  delete "/logout", to: "sessions#destroy"

  scope :menu, as: "menu" do
    resources :items, param: :item_name
    resources :categories, param: :category_name
  end

  scope :admin, as: "admin" do
    get "/dashboard", to: "admin#show"
  end

  resources :cart_items, only: [:create, :update, :destroy]
  get "/cart", to: "cart_items#index"
  post "/checkout", to: "orders#create"

  resources :orders do
    member do # for an individual order
      get "cancel"
      get "paid"
      get "complete"
    end
  end

  get "errors/file_not_found"
  get "errors/unprocessable"
  get "errors/internal_server_error"

  match "/404", to: "errors#file_not_found", via: :all
  match "/422", to: "errors#unprocessable", via: :all
  match "/500", to: "errors#internal_server_error", via: :all
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>DinnerDash</title>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
  </head>
  <body>
    <nav class="navbar navbar-default" id="navbar-color">
      <div class="container-fluid">
        <!-- Brand and toggle get grouped for better mobile display -->
        <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a class="navbar-brand" <%= link_to "The Dirty Cookie", root_path %></a>
        </div>
        <!-- Collect the nav links, forms, and other content for toggling -->
        <div class="collapse navbar-collapse navbar-right" id="bs-example-navbar-collapse-1">
          <ul class="nav navbar-nav">
            <li class="dropdown">
              <a href="#" class="dropdown-toggle" id="filter_items" data-toggle="dropdown" role="button" aria-expanded="false">
                Menu<span class="caret"></span></a>
                <ul class="dropdown-menu" role="menu">
                  <li><%= link_to "All Items", menu_path %><span class="sr-only"></span></li>
                    <% all_categories.each do |category| %>
                    <li><%= link_to category.name.capitalize, menu_category_path(category.name) %></a></li>
                    <% end %>
                  </li>
                </ul>
              </li>
              <li><%= link_to "Account", account_path %><span class="sr-only"></span></li>
              <li><%= link_to "<span class='glyphicon glyphicon-shopping-cart' aria-hidden='true'>".html_safe, cart_path %></li>
                <% if current_user.try(:role) == "admin" %>
                <li><%= link_to "Dashboard", admin_dashboard_path %><span class="sr-only"></span></li>
                <% end %>
                <% if current_user %>
                <li><%= link_to "Sign out", logout_path, method: :delete %></li>
                <% else %>
                <li><%= link_to "Sign in", login_path %></li>
                <% end %>
              </ul>
            </div><!-- /.navbar-collapse -->
          </div><!-- /.container-fluid -->
        </nav>
    <div class="container">
      <div class="row flash">
        <%= flash_messages %>
      </div>

      <%= yield %>
    </div>
  </body>
</html>